# Generated by Django 2.2.4 on 2019-08-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='none', width_field='width_field')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
