# Generated by Django 2.2.4 on 2019-08-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20190815_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('pk',)},
        ),
    ]
