# Generated by Django 2.2.4 on 2019-08-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ('code',), 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='created',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='tags_reviewed',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='modified',
        ),
    ]
